# -*- coding: utf-8 -*-
"""GDrives Copy

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HzM-OSYq8faMWncnYerBtTzqsq0Dgvbw
"""

from google.colab import drive
drive.mount('/gdrive')

"""Test"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/gdrive')

# %cd /gdrive/My Drive/0/2019 (ARC)

pwd

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/Shareddrives/Transaction Count

!cp -r '/gdrive/Shareddrives/Transaction Count/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives'

"""Copy a Drive  '/gdrive/Shareddrives/folder/.' -- means all files and folders under folder"""

!cp -r '/gdrive/Shareddrives/Transaction Count' '/gdrive/Shareddrives/Personal Stuffs'

!cp -r '/gdrive/Shareddrives/MRSGI WAY 2.0 Project Shared Drive/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/MRSGI WAY 2.0 Project Shared Drive'

!cp -r '/gdrive/Shareddrives/References' '/gdrive/Shareddrives/Personal Stuffs/GDrives'

!cp -r '/gdrive/Shareddrives/RMS Opt.- Data Enrichment Project Shared Drive' '/gdrive/Shareddrives/Personal Stuffs/GDrives'

!cp -r '/gdrive/Shareddrives/Merchandising Team Shared Drive' '/gdrive/Shareddrives/Personal Stuffs/GDrives'

!cp -r '/gdrive/Shareddrives/Supermarket' '/gdrive/Shareddrives/Personal Stuffs/GDrives'

!cp -r '/gdrive/Shareddrives/BusinessShared/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/BusinessShared'

!cp -r '/gdrive/Shareddrives/_Basic Grocery Critical Path Audit Repositories_/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/Basic Grocery Critical Path Audit Repositories'

!cp -r '/gdrive/Shareddrives/_Fresh Critical Path Audit Repositories_/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/Fresh Critical Path Audit Repositories'

!cp -r '/gdrive/Shareddrives/BI Team  (Business Side)/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/BI Team  (Business Side)'

!cp -r '/gdrive/Shareddrives/Executive Reports/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/Executive Reports'

!cp -r '/gdrive/Shareddrives/QVF Files/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/QVF Files'

!cp -r '/gdrive/Shareddrives/RI REPOSITORY/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/RI REPOSITORY'

"""My Drive back-up copy as of 4.2.21"""

from google.colab import drive
drive.mount('/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /gdrive/My Drive/My Drive

pwd

!cp -r '/gdrive/My Drive/My Drive/.' '/gdrive/Shareddrives/Personal Stuffs/GDrives/My Drive'